export const ADS = {
    PENDING:'PENDING',
    ACTIVE:'ACTIVE',
    DELETED:'DELETED',
    ACCEPTED_REQUEST:'ACCEPTED_REQUEST',
    CONTRACT_RUNNING:'CONTRACT_RUNNING',
    PAID:'PAID'
};

export const RENT_REQUESTS = {
    OPEN:'OPEN',
    ACCEPTED:'ACCEPTED',
    DELETED_AD:'DELETED_AD',
    OTHER_ACCEPTED:'OTHER_ACCEPTED',
    CONTRACT_RUNNING:'CONTRACT_RUNNING',
    WAITING_PAYMENT:'WAITING_PAYMENT',
    WAITING_OPERATOR:'WAITING_OPERATOR',
    COMPLETED:'COMPLETED',
    DELETED:'DELETED'
};

export const CONTRACTS = {
    PENDING:'PENDING',
    RUNNING:'RUNNING',
    OWNER_BROKEN:'OWNER_BROKEN',
    TENANT_BROKEN:'TENANT_BROKEN',
    FINISHED:'FINISHED'
};