export const availableParts = {
    "basic_bigwave": {"amount": 0, "alias": "basic_bigwave", "ID": 21},
    "basic_slope": {"amount": 0, "alias": "basic_slope", "ID": 23},
    "basic_stepslope": {"amount": 0, "alias": "basic_stepslope", "ID": 25},
    "basic_halframp": {"amount": 0, "alias": "basic_halframp", "ID": 26},
    "basic_loop": {"amount": 0, "alias": "basic_loop", "ID": 28},
    "basic_centrebump": {"amount": 0, "alias": "basic_centrebump", "ID": 31},
    "basic_cylinder": {"amount": 0, "alias": "basic_cylinder", "ID": 33},
    "basic_curve": {"amount": 0, "alias": "basic_curve", "ID": 34},
    "basic_concave_corner": {"amount": 0, "alias": "basic_concave_corner", "ID": 35},
    "basic_sidebend": {"amount": 0, "alias": "basic_sidebend", "ID": 36},
    "basic_hole": {"amount": 0, "alias": "basic_hole", "ID": 37},
    "basic_floor": {"amount": 0, "alias": "basic_floor", "ID": 38},
    "basic_floor_teeth": {"amount": 0, "alias": "basic_floor_teeth", "ID": 39},
    "basic_ramp": {"amount": 0, "alias": "basic_ramp", "ID": 40},
    "basic_wall": {"amount": 0, "alias": "basic_wall", "ID": 41},
    "basic_border": {"amount": 0, "alias": "basic_border", "ID": 43},
    "basic_floor_dpath": {"amount": 0, "alias": "basic_floor_dpath", "ID": 49},
    "basic_cube": {"amount": 0, "alias": "basic_cube", "ID": 52},
    "basic_small_border": {"amount": 0, "alias": "basic_small_border", "ID": 55},
    "basic_ramp_border": {"amount": 0, "alias": "basic_ramp_border", "ID": 56},
    "basic_low_slope": {"amount": 0, "alias": "basic_low_slope", "ID": 57},
    "basic_concave_halfcorner": {"amount": 0, "alias": "basic_concave_halfcorner", "ID": 61},
    "basic_thinpath1": {"amount": 0, "alias": "basic_thinpath1", "ID": 62},
    "basic_border_plank": {"amount": 0, "alias": "basic_border_plank", "ID": 63},
    "egypt_border": {"amount": 0, "alias": "egypt_border", "ID": 67},
    "egypt_bigwave": {"amount": 0, "alias": "egypt_bigwave", "ID": 69},
    "egypt_centrebump": {"amount": 0, "alias": "egypt_centrebump", "ID": 70},
    "egypt_cylinder": {"amount": 0, "alias": "egypt_cylinder", "ID": 71},
    "egypt_concave_corner": {"amount": 0, "alias": "egypt_concave_corner", "ID": 72},
    "egypt_concave_halfcorner": {"amount": 0, "alias": "egypt_concave_halfcorner", "ID": 73},
    "egypt_cube": {"amount": 0, "alias": "egypt_cube", "ID": 74},
    "egypt_curve": {"amount": 0, "alias": "egypt_curve", "ID": 75},
    "egypt_floor": {"amount": 0, "alias": "egypt_floor", "ID": 76},
    "egypt_floor_teeth": {"amount": 0, "alias": "egypt_floor_teeth", "ID": 77},
    "egypt_floor_dpath": {"amount": 0, "alias": "egypt_floor_dpath", "ID": 78},
    "egypt_halframp": {"amount": 0, "alias": "egypt_halframp", "ID": 79},
    "egypt_hole": {"amount": 0, "alias": "egypt_hole", "ID": 80},
    "egypt_loop": {"amount": 0, "alias": "egypt_loop", "ID": 81},
    "egypt_low_slope": {"amount": 0, "alias": "egypt_low_slope", "ID": 82},
    "egypt_ramp": {"amount": 0, "alias": "egypt_ramp", "ID": 83},
    "egypt_ramp_border": {"amount": 0, "alias": "egypt_ramp_border", "ID": 84},
    "egypt_sidebend": {"amount": 0, "alias": "egypt_sidebend", "ID": 85},
    "egypt_small_border": {"amount": 0, "alias": "egypt_small_border", "ID": 87},
    "egypt_stepslope": {"amount": 0, "alias": "egypt_stepslope", "ID": 88},
    "egypt_thinpath1": {"amount": 0, "alias": "egypt_thinpath1", "ID": 89},
    "egypt_wall": {"amount": 0, "alias": "egypt_wall", "ID": 90},
    "egypt_border_plank": {"amount": 0, "alias": "egypt_border_plank", "ID": 91},
    "egypt_slope2": {"amount": 0, "alias": "egypt_slope2", "ID": 105},
    "image": {"amount": 0, "alias": "image", "ID": 105},
};
export const necessaryParts = {
//    "Skybox1":{"alias":"Skybox1","amount":1},
    "basic_floor": {"alias": "basic_floor", "amount": 12},
    "basic_hole": {"alias": "basic_hole", "amount": 1},
    "image": {"alias": "image", "amount": 1},
    "basic_border": {"alias": "basic_border", "amount": 6}
}